markdown: kramdown
permalink: pretty
title: Security in a Box
tagline: Content as Code work on SIAB.
description: Content as Code work on SIAB.
url: 'http://contentascode.github.io'
baseurl: /siab
author:
  name: Your Name
  url: 'https://twitter.com/yourtwitter'
defaults:
  - scope:
      path: ''
    values:
      layout: default
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false
redcarpet:
  extensions:
    - tables
    - autolink
    - strikethrough
    - space_after_headers
    - with_toc_data
    - fenced_code_blocks
    - lax_spacing
    - smart
github:
  current_branch: master
  repository_url: 'https://github.com/contentascode/docsmith-init'
gems:
  - jekyll-sitemap
  - jekyll-gist
username: USER
owner: ORG
repo: REPO
safe: false
lsi: false
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - '*.Rmd'
  - vendor
  - .travis.yml
prose:
  rooturl: md